### ISSUE TITLE
Non-Error exception captured with keys: error

### ISSUE THREAD

**Issue by techyrajeev** [getsentry/react-native-sentry#391]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v9.7.1
5.7.1

```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

    "react": "16.2.0",
    "react-native": "0.53.0",
    "react-native-sentry": "^0.35.3",
---
I am getting lots of crashes with this error -
```
 } else if (isPlainObject(ex)) {
      // If it is plain Object, serialize it manually and extract options
      // This will allow us to group events based on top-level keys
      // which is much better than creating new group when any key/value change
      options = this._getCaptureExceptionOptionsFromPlainObject(options, ex);
      ex = new Error(options.message);
    } else {
      // If none of previous checks were valid, then it means that
      // it's not a plain Object
      // it's not a valid ErrorEvent (one with an error property)
      // it's not an Error
```

**Comment by devladinci** [comment]
👍 Same here

**Comment by HazAT** [comment]
Can you link a Sentry event here please?

**Comment by techyrajeev** [comment]
Attached a screen shot.

**Comment by techyrajeev** [comment]
<img width="1248" alt="screen shot 2018-04-24 at 9 55 32 am" src="https://user-images.githubusercontent.com/4118032/39166721-cb6d773e-47a8-11e8-8544-ae72d3d2e635.png">

**Comment by HazAT** [comment]
The next release (which is currently building) should fix this.
Stay tuned for `0.36.0`.

**Comment by glebmachine** [comment]
Still got this error:
`Non-Error exception captured with keys: error, headers, message, name, ok…`

**Comment by ldgarcia** [comment]
@HazAT Here is a link for a similar error ("_Error: Non-Error exception captured with keys: errorCode, errorMessage…_"):

https://sentry.io/share/issue/1d9a134305c747f6a134880e134e51d5/

**Comment by jackrvaughan** [comment]
Also still getting this for an angular6 frontend:

`Non-Error exception captured with keys: error, headers, message, name, ok…`

**Comment by glebmachine** [comment]
This is not specific to react-native, i got this on angular 6 application

**Comment by jackrvaughan** [comment]
@glebmachine Yep, agreed - just this issue is in the `react-native-sentry` repo

**Comment by lcortess** [comment]
Hello, I have the same issue with an angular 6 app, my Raven-js version is `3.26.3` and my sentry version `9.0.0`

**Comment by zaiddabaeen** [comment]
Any updates on this?

**Comment by lilywang711** [comment]
Happening on vue2 with "raven-js": "^3.26.4"

**Comment by lilywang711** [comment]
hey,I found the reason in my project,It doesn't matter with the version or framwork.
The correct format to throw the error is `throw new Error(err.data.message)`, not `throw new Error(err)`
Which means that the error should be a `String`

After I modified this, this error has never happened again.
hope this helps

**Comment by vdespa** [comment]
@lilywang711 I would like to disagree, the error can be an Error, ErrorEvent or string.
While only setting a string may work for you, it is not a solution for everybody.

**Comment by mehulmpt** [comment]
Happens on Reactjs web app too

**Comment by studentIvan** [comment]
same here

**Comment by benvinegar** [comment]
So, if this has occurred, it means that Sentry/Raven doesn't believe the error is an `Error` but rather some other object. And we iterate through the keys to give you a clue what we caught instead.

Note that if you're trying to capture a custom `Error` (e.g. a subclass, whether defined by your code or the framework code), there's a specific way to do this to make sure it also is detectable as an `Error`. You can verify it works by verifying `MyError instanceof Error` evaluates to true.

For example, @jackrvaughan wrote:

> Non-Error exception captured with keys: error, headers, message, name, ok…

This means that Sentry/Raven encountered a JavaScript object with this shape:

```
{
  error: { ... /* some genuine error object probably? */ ... },
  headers: { ... /* some sub-object probably? */ },
  message: '???',
  name: '???',
  ...
}
```

(That doesn't look like an `Error` proper to me.)

**Comment by acevedomiguel-ai** [comment]
on Node `v10.7.0` using `"@sentry/node": "^4.0.3"` I got this on my code (Custom error)
```
class AppError extends Error {
    constructor(error) {
        super(error.err_msg);
        this.name = this.constructor.name;
        Error.captureStackTrace(this, this.constructor);
    }
}
```

then throw
```
throw new AppError({ err_msg: "test d" })
```

and I get:
```
Error@sentry.node.dist:backend in NodeBackend.<anonymous>
errorNon-Error exception captured with keys: name
```

**Comment by acevedomiguel-ai** [comment]
I tried this solution https://github.com/getsentry/sentry-javascript/issues/1260#issuecomment-373398920 but still getting something like:

`errorNon-Error exception captured with keys: [object has no keys]`

**Comment by kamilogorek** [comment]
I'm not able to reproduce this issue locally.

Test code:
```js
const Sentry = require("@sentry/node");

Sentry.init({
  dsn: "http://foo@bar.com/42",
  beforeSend(event) {
    console.log(JSON.stringify(event, null, 2));
    return null;
  }
});

class AppError extends Error {
  constructor(error) {
    super(error.err_msg);
    this.name = this.constructor.name;
    Error.captureStackTrace(this, this.constructor);
  }
}

throw new AppError({ err_msg: "test d" });
```

I also tried direct `captureException` instead of a `throw`

```js
Sentry.captureException(new AppError({ err_msg: "test d" }));
```

and it worked just fine as well.

Logs:
```js
{
  "exception": {
    "values": [
      {
        "stacktrace": {
          "frames": [// removed to not take too much space]
        },
        "type": "AppError",
        "value": "test d"
      }
    ]
  },
  "message": "AppError: test d",
  "extra": {
    "AppError": {
      "name": "AppError"
    }
  },
  // rest of the event
}
```

Tested on `@sentry/node@4.0.6 (latest)` as well as on mentioned `@sentry/node@4.0.3`.
And node versions `8.11.1`, `10.7.0` and `10.11.0 (latest)`. All tests with the same results.

**Comment by dandanbu3** [comment]
happened on vue2.6 with "raven-js 3.27.0"

**Comment by richardshergold** [comment]
We're getting these errors in our Ionic application with raven.js 3.26.4

**Comment by kamilogorek** [comment]
@richardshergold if you're able to reproduce it locally, use
```js
init({
  dsn: 'your_dsn',
  beforeSend(event, hint) {
    console.log(hint.originalException);
    return event;
  }
})
```

to investigate what's the shape of the error and update it appropriately.

**Comment by richardshergold** [comment]
@kamilogorek thanks - I haven't been able to produce locally actually  If I added that code in Production though presumably I would see that info in the console breadcrumbs?

**Comment by kamilogorek** [comment]
> I would see that info in the console breadcrumbs?

No, we are excluding logging from our own callbacks, otherwise, it could create an infinite loop.

You can do something like:

```js
Sentry.init({
  dsn: 'your_dsn',
  beforeSend(event, hint) {
    if (event.message.startsWith('Non-Error exception captured') && hint.originalException.error) {
      Sentry.withScope((scope) => {
        Sentry.setExtra('nonErrorException', true);
        Sentry.captureException(hint.originalException.error);
      });
      return null;
    }
    return event;
  }
})
```

This'll prevent those errors from being sent to Sentry and will catch `originalException.error` instead.
You can do any filtering/modifications in `beforeSend` or even better, an event processor. https://docs.sentry.io/platforms/javascript/#eventprocessors

**Comment by Riccardo-Andreatta** [comment]
@kamilogorek I have those TypeScript errors with the above code:

`Property 'setExtra' does not exist on type 'typeof import(`_sentry browser node module path_`)`

And

`Property 'error' does not exist on type 'Error'.`

Any idea?

**Comment by kamilogorek** [comment]
@Riccardo-Andreatta yeh, my example had a bug 😅 It should be `scope.setExtra`, not `Sentry.setExtra`.
Regarding first error, it's because we assume `originalException` is an Error object, but in case of this thread, it's a non-standard one (there's no `Error.error` in the native implementation).

```js
interface ExtendedError extends Error {
  error: Error;
}
```

and then

```js
if (!hint.originalException) return event;

const customError = (hint.originalException as ExtendedError).error;

if (event.message.startsWith('Non-Error exception captured') && customError) {
  Sentry.withScope((scope) => {
    scope.setExtra('nonErrorException', true);
    Sentry.captureException(customError);
  });
  return null;
}
```

**Comment by richardshergold** [comment]
@kamilogorek just looking at this again - we are using Raven.js - can these events be filtered out in the same way using Raven?

**Comment by kamilogorek** [comment]
@richardshergold you can filter them out (there's `dataCallback` method), but you wont have an access to the original exceptiion in case you'd like to override it.

**Comment by richardshergold** [comment]
@kamilogorek ok thank you.  Just so I am understanding (I am in the process of deciding whether or not to move from using raven.js to the Cordova plugin and the new SDK - ours is an Ionic app) - why, with Raven, won't I have access to the original exception?  (and would this be a good reason to move from raven.js?)

**Comment by kamilogorek** [comment]
There's no mechanism that passes original instance that was used to create a Sentry event. Only new v4 SDK has this feature. They are called hints https://docs.sentry.io/platforms/javascript/#hints

**Comment by cihati** [comment]
@kamilogorek @HazAT I'm having this issue in react-native-sentry. How can I do the `beforeSend` trick @kamilogorek suggested? I do not see `beforeSend` at https://docs.sentry.io/clients/react-native/config/ (even though it's mentioned in JS, https://docs.sentry.io/platforms/javascript/?platform=node#eventprocessors )?

My error is `Non-Error exception captured with keys: error, meta, payload, type` (when I click on the blue + symbol in below, I only see "<recursion limit hit>")
![image](https://user-images.githubusercontent.com/461998/54123633-226c8b00-43f8-11e9-8298-5a8bc2090a3a.png)

**Comment by kamilogorek** [comment]
@cihati this is exactly what you should see, as we are trying to provide any usable information that can be used to find out where is the cause :)

In this case, you somewhere do `throw obj` where `obj` is the thing from the log above.

`react-native-sentry` doesn't have `beforeSend` with the `hint`, but `setDataCallback` instead as it's not part of our core `sentry-javascript` SDK yet. 

```
Sentry.setDataCallback((event) => {
  // you can inspect and override the event here as described in the comments above
  return event;
});
```

**Comment by valerii-cognite** [comment]
Received the following error `Non-Error exception captured with keys: message, status`

**Comment by kamilogorek** [comment]
@valerii-cognite then you have `throw { message: '', status: '' }` somewhere in your code, where the only thing you should `throw` is error instance

**Comment by DataGreed** [comment]
So why exactly is this closed? When was it fixed if it was?

I get the same problem on 0.42 (or was it fixed after this version?)

My code:

```
try {
      active = await this.someMethod()
    } catch (error) {
      alert(error.message)
      Sentry.captureException(error)
      this.setState({
        isDongSomething: false
      })
    }
```

With this code I get `Non-Error exception captured with keys: default` in Sentry

**Comment by romelgomez** [comment]
For Angular I having the same problem with this code. I find out that returning a new empty error instance produced this error:

```typescript
@Injectable()
export class SentryErrorHandler implements ErrorHandler {

  constructor() { }

  handleError(error: any) {

    if (environment.production) {
      Sentry.captureException(error.originalError || error);
    }

    return new ErrorHandler();
  }

}
```
So I fixed with this solution: 

```typescript
@Injectable()
export class SentryErrorHandler implements ErrorHandler {

  constructor() { }

  handleError(error: any) {

    if (environment.production) {
      Sentry.captureException(error.originalError || error);
    } else {
      console.error(error);
    }

  }

}

```

**Comment by hnrchrdl** [comment]
i found [this answer](https://github.com/getsentry/sentry-javascript/issues/2546#issuecomment-703331367) helpful from a related issue.

**Comment by himajaM** [comment]
@romelgomez  where to place this solution code in angular 8

@Injectable()
export class SentryErrorHandler implements ErrorHandler {

  constructor() { }

  handleError(error: any) {

    if (environment.production) {
      Sentry.captureException(error.originalError || error);
    } else {
      console.error(error);
    }

  }

}


and one more question is :::

I think it is not necessary to console the error in production environment ...

**Comment by romelgomez** [comment]
Hi @himajaM ,  I think, what i can remember is:  

e.g: https://sentry.io/for/angular/

Instead of using `ErrorHandler` class, I passed a new class `SentryErrorHandler`

```
@Injectable()
export class SentryErrorHandler implements ErrorHandler {

  constructor() { }

  handleError(error: any) {

    if (environment.production) {
      Sentry.captureException(error.originalError || error);
    } else {
      console.error(error);
    }

  }

}
```

`environment.production` will be `true` in production and then the error will be registed in Sentry, other side  (develoment )will be log in the console of developer and not in Sentry, this is for avoid send develoment errors saved in Sentry API

**Comment by himajaM** [comment]
Thanks for your response...

Is this the only way (i.e console.log(error)) to avoid logs in sentry?


Best regards,
Himaja Marada
Sails Software Solutions
(+91) 9640693045
himaja@sails.solutions
